# Generated by Django 4.1.3 on 2022-11-30 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('secondaryPhone', models.CharField(max_length=20, null=True)),
                ('passcode', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userType', models.CharField(choices=[('Customer', 'Customer'), ('Owner', 'Owner')], default='Customer', max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('isPhoneVerified', models.BooleanField(default=False)),
                ('last_loggedIn', models.DateTimeField(auto_now=True)),
                ('mobile_verify_OTP', models.CharField(blank=True, max_length=10, null=True)),
                ('djangoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, null=True)),
                ('car_pic', models.ImageField(upload_to='')),
                ('fuel_type', models.CharField(choices=[('Ev', 'Ev'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=6)),
                ('rent_price_hour', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.basicuser')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_trip', models.DateTimeField(auto_now_add=True)),
                ('end_trip', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.basicuser')),
                ('rent_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.car')),
            ],
        ),
    ]
