# Generated by Django 4.1.3 on 2022-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_price_hour',
            field=models.IntegerField(null=True),
        ),
    ]
